# change this to the name of the repository and have it in all lower caps
baseurl: "/brisbane"

# change this to the name of your city
city: Brisbane

# color names taken from http://materializecss.com/color.html
# append '-text' to color2 names and prepend accent/darken with 'text-'
city_color:  blue darken-1
city_color2: yellow-text
logo_color: black # either black or white